### ISSUE TITLE
serialbluetooth.on('data', buffer) cuts the incoming string

### ISSUE THREAD

**Issue by ladislas** [eelcocramer/node-bluetooth-serial-port#10]
Hi there!
First I want to thank you for your great work! :) It works like a charm.

Except I'm having some trouble with the on data event.

my code is as follow:

``` javascript
serial.connect(address, channel, function() {
    console.log('Connected. Receiving data...');
    serial.on('data', function(buffer) {
        console.log("New incoming string");
        var buf = buffer.toString('utf-8');
        console.log("String = " + buf);
});
```

It should look like this:

```
New incoming string
String = { "accel":{"x":76,"y":-2,"z":217},"gyro":{"yaw":109,"pitch":19,"roll":0}}
```

And this is what I get:

```
New incoming string
String = {
New incoming string
String = "accel":{"x":76,"y":-2,"z":217},"gyro":{"yaw":109,"pitch":19,"roll":0
New incoming string
String = }}
```

Do you have any idea of what I'm doing wrong?

**Comment by Eriatolc** [comment]
Hi everyone!

First, thanks for your amazing job in this library. It works perfectly for me.

I was in the same situation as @ladislas and my messages don't have any new line char `\n` that can be added at the end.
I just want to add another code example for people who are struggling with this problem. Your serial data should start with a **"start" char** and end with an **"end" one**.
To detect this, you can use a **regular expression**.

_Example:_
For me, each data I am receiving start with the char `0x02` and end with the `0x03` char. If they appear in the middle of the message, they are escaped.
Thus, the code given by @ladislas becomes this:

```javascript
btSerial.connect(address, channel, function () {
    var buffer = "";
    var pattern = new RegExp(/^02.*03$/);

    btSerial.on('data', function (data) {
        buffer += data.toString('hex');
        // my messages are encoded in hexa, but you can put here any encoding you want :)
        if (pattern.test(buffer)) { // test with a regex
            handleData(buffer);
            console.log("New incoming string");
            console.log('String: ', buffer);
            buffer = "";
        }
    });
}, function () {
     console.log("Cannot connect");
});
```

Maybe it can help some people in the future :)

**Comment by eelcocramer** [comment]
Thank you for the additional example.
