### ISSUE TITLE
Intel Edison Bluetooth

### ISSUE THREAD

**Issue by pratikus** [eelcocramer/node-bluetooth-serial-port#102]
Hello Eelco,

We are kind of stuck at a critical point in the project and are hoping you could point us in the right direction.

We are trying to get two Intel Edisons to talk to each other/cellphone via Bluetooth.

Here is an image of our test-setup:
![img_2592](https://cloud.githubusercontent.com/assets/15786664/16967154/be150238-4dd5-11e6-9255-c1275d037585.JPG)

Here is our main program: 
![testdotjs screenshot](https://cloud.githubusercontent.com/assets/15786664/16967161/c3d8297a-4dd5-11e6-82a7-7b6a9c6c40ac.png)
![cramer sbsp main](https://cloud.githubusercontent.com/assets/15786664/16967170/ca690250-4dd5-11e6-8e01-cd09810404b4.jpg)

Here is a test.js output:
![testdotjs screenshot](https://cloud.githubusercontent.com/assets/15786664/16967201/e5627fc8-4dd5-11e6-95a6-000ee0a07bd5.png)

So far we have only been able to connect to an iphone via Bluetooth (please see main program link). We are not able to connect the Edison’s to each other. As such, we don’t know if we can send data back and forth with your module.

Really hoping you can get involved in this project!

**Comment by eelcocramer** [comment]
Hi. Looks like a nice project! I've received your mail via linkedin as well but prefer to answer this here in the true spirit of open source 👍🏼

Have you checked the [FAQ](https://github.com/eelcocramer/node-bluetooth-serial-port/issues?utf8=✓&q=label%3AFAQ%20)?

FAQ entry #69 might be relevant for your: this library is client side only. If you have BT serial port service running somewhere you can use this library to connect to it. I'm unaware of any node modules that implement the server side.

I hope this helps.

**Comment by noahko123** [comment]
Hi Eelco,

Would the github project for noble BLE (https://github.com/sandeepmistry/noble) work as the server for your project?

**Comment by eelcocramer** [comment]
No, that is a Bluetooth Low Energy implementation where this client implements the Bluetooth serial port profile. These are completely different Bluetooth profiles.

**Comment by noahko123** [comment]
Thanks for the quick response.  You've been a big help!

**Comment by eelcocramer** [comment]
No problem I'm glad I could help
