### ISSUE TITLE
inquire() asynch. function

### ISSUE THREAD

**Issue by danneboom** [eelcocramer/node-bluetooth-serial-port#121]
How does inquire() search for devices? Does it last a certain time? 
I want to search always for new devices. I guess i have to use setInterval(function(){
btSerial.inquire();
})
but which interval should i choose? Is there another possibility?

**Comment by eelcocramer** [comment]
Inquire emits a [`finished` event](https://github.com/eelcocramer/node-bluetooth-serial-port#event-finished) when the search did finish. You can use that event to trigger a new scan.

**Comment by danneboom** [comment]
aaah. so i'll use btSerial.on('finished', function(){ btSerial.inquire(); });
Correct? Thanks

**Comment by eelcocramer** [comment]
👍🏼
