### ISSUE TITLE
Run Arduino Yum

### ISSUE THREAD

**Issue by DominicWrege** [eelcocramer/node-bluetooth-serial-port#124]
Can I run use this on my Arduino Yún which uses an external HM-10 Bluetooth 4.0 module?

**Comment by eelcocramer** [comment]
If it runs Linux and you can install the pre-requests it should work I guess but I've no experience with this myself.

**Comment by DominicWrege** [comment]
The Arduino runs Linux OpenWrt and the BT module works over a normal serial connection.

**Comment by eelcocramer** [comment]
I have no experience with OpenWrt so I cannot tell you anything specific about that. Maybe you can check the Arduino forum about this?

**Comment by eelcocramer** [comment]
Had any luck? Maybe someone else will run into the same issue some day? 👍
