### ISSUE TITLE
Question about system calls

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [eelcocramer/node-bluetooth-serial-port#129]
In this code snippet:

```javascript
BluetoothSerialPort.prototype.close = function () {
    if (this.connection) {
        this.connection.close(this.address);
        this.connection = undefined;
    }

    this.emit('closed');
};
```
`this.connection.close(this.address)` somehow breaks the app. it happens rarely but I cannot prevent this. I've tried to put try catch here but it was not successful. Also similar crash I'm receiving when inquiry happens. Also rarely. This methods calls binary. Is this could be handled somehow?

The environment is Electron and unfortunately there is no logs. I got this conclusion manually with breakpoints. I know that when something wrong happens the row `this.connection = undefined;` is not reached and last executed row is previous. Problem could be in the device but my question is related if something wrong happens in binary is there way to prevent it. If try catch of this row was able to do something we would be able to see some error.

About the platform, it doesn't matter, it happens in the same way under mac and windows. Probably reproducing of this problem will be a problem.

**Comment by eelcocramer** [comment]
Is `this.address` set to a value when this occurs?
