### ISSUE TITLE
Question: does this library support CSR Harmony wireless software stack on windows?

### ISSUE THREAD

**Issue by gengshenghong** [eelcocramer/node-bluetooth-serial-port#132]
Any idea? It seems like when using CSR Harmony wireless software stack with an CSR bluetooth dongle, this library cannot scan the device (no device found). And with Microsoft default driver(software stack), it works as expected.

Thanks,
Shenghong

**Comment by eelcocramer** [comment]
I have no idea. This library just wraps around the Microsoft .NET bluetooth APIs.
