### ISSUE TITLE
Set serial port configuration

### ISSUE THREAD

**Issue by sandangel** [eelcocramer/node-bluetooth-serial-port#142]
Is there any way to set serial port configuration like baudrate, parity, stopbit, databit....
like:

const btSerial = new (require('bluetooth-serial-port')).BluetoothSerialPort(options: {
  baudRate: 9600,
  parity: none,
  stopBit: 1,
  dataBit: 8
});

At this time, btSerial instance is only support for 9600 baudrate parity none, stopbit 1 and databit 8. If server serial port config is different, data can't not be read as string.

**Comment by eelcocramer** [comment]
I believe there is no way to do that trough the APIs of the various platforms (linux, osx, windows). From what find it is mostly specific to the bluetooth modules. I won't be adding support for this configuration myself but I'm happy to accept a pull request that adds this functionality.
