### ISSUE TITLE
Is there a way to make it running under Android / Termux?

### ISSUE THREAD

**Issue by sergii-savchenko** [eelcocramer/node-bluetooth-serial-port#146]
I'm trying to write a little programs under Termux. Is there any way to make your module running?

**Comment by eelcocramer** [comment]
Not sure. On Linux this library depends the bluez bluetooth stack. On Android bluez is not available. Maybe this could help you: https://bluez-android.github.io but I have no experience with it.

**Comment by lefuturiste** [comment]
Same question here!
