### ISSUE TITLE
Get Channels of found device

### ISSUE THREAD

**Issue by dominicrico** [eelcocramer/node-bluetooth-serial-port#147]
Is there a way to see the channels of a device on found or after connecting?
I want to connect to a specific service and this is atm only possible after pairing.

Thank you for your help!

**Comment by eelcocramer** [comment]
I do not think that is not possible before pairing. Then again, I never checked it against the specs. If this should be possible according to the specs I'm willing to look into it.

**Comment by dominicrico** [comment]
Thanks for your reply. I will check the specs and let you know!

**Comment by eelcocramer** [comment]
Might relate to #122
