### ISSUE TITLE
On data buffer returning 2 values instead of one

### ISSUE THREAD

**Issue by samuelguesnier** [eelcocramer/node-bluetooth-serial-port#153]
Hello, I want to get temperature from the arduino, but when I try to read it in node, instead of having "24", I get "2" and lower "4".

**Comment by eelcocramer** [comment]
It is very well possible to that data send over the Bluetooth connection is received in separate `data` events. It is up to you to merge or spit the data in the buffer according to your needs.

You might want to add a delimiter into you data to distinguish one reading from another.

See also the FAQ: #10

**Comment by samuelguesnier** [comment]
Thank you very much , it works. You are doing a super job ! :+1:

**Comment by eelcocramer** [comment]
Thanks 😊
