### ISSUE TITLE
How to solve the problem of Chinese garbled

### ISSUE THREAD

**Issue by vtkom** [eelcocramer/node-bluetooth-serial-port#168]
����3s
bluetooth1.1.js:19 Found: 1C:CD:E5:8C:05:88 with name ����3s1
bluetooth1.1.js:18 RG-BLE-22
bluetooth1.1.js:19 Found: 1E:03:E0:81:39:BB with name RG-BLE-222
events.js:86 finished

**Comment by vtkom** [comment]
How to solve the problem of Chinese scrambled code

**Comment by eelcocramer** [comment]
Thank you for reporting. What platform are you using?

**Comment by eelcocramer** [comment]
https://github.com/song940/node-bluetooth/issues/11
