### ISSUE TITLE
BLE

### ISSUE THREAD

**Issue by zhaiyuzhai** [eelcocramer/node-bluetooth-serial-port#170]
I would like to ask if this version can support Bluetooth 4.0 (Bluetooth Low Energy)

**Comment by eelcocramer** [comment]
This module is voor classic bluetooth only. There are other node modules, like [noble](https://github.com/sandeepmistry/noble), that enable you to use BLE in your applications.

**Comment by zhaiyuzhai** [comment]
thanks
