### ISSUE TITLE
Error reading from connection

### ISSUE THREAD

**Issue by zhaiyuzhai** [eelcocramer/node-bluetooth-serial-port#172]
when i connect one device it seems ok . however，when i connect two or more devices at one time and read data from the devices it may cause the error like that “Error: Error reading from connection
    at Error (native)”。what is wrong？

**Comment by eelcocramer** [comment]
Hi, you should re-recreate the connection every time you create a new connection to a device. Please refer to #90 and #162 for more information.

**Comment by zhaiyuzhai** [comment]
thanks
