### ISSUE TITLE
program crashes if no Bluetooth available 

### ISSUE THREAD

**Issue by zhaiyuzhai** [eelcocramer/node-bluetooth-serial-port#186]
platform：win10_64bit;
app:electron1.7.9;
error:Process finished with exit code -1073741819 (0xC0000005)

My application is based on electron. When there is no proper bluetooth, the module will cause my app to crash。Someone to solve this problem, thank you very much？

**Comment by zhaiyuzhai** [comment]
When I call btSerial.inquireSync().What seems to be blocking my app for about three seconds.
I still don't have a good solution to it

**Comment by eelcocramer** [comment]
If you don’t want a synchronized call you should use inquire which works async.

**Comment by zhaiyuzhai** [comment]
@eelcocramer Thank you very much for your help, but now I have a difficulty that when bluetooth is not available, the program will report an error and quit directly. As shown below.
Process finished with exit code -1073741819 (0xC0000005)；
I have seen#136， use try catch statements around btSerial.inquire() or btSerial.inquireSync() cannot work. I dont know how to catch the error  ，how to stop the program from crashing。

**Comment by zhaiyuzhai** [comment]
@eelcocramer Bluetooth-serial-port donot has error Event，Hopefully you can add it in the next release
