### ISSUE TITLE
Deprecate NAN and use N-API instead

### ISSUE THREAD

**Issue by FrogTheFrog** [eelcocramer/node-bluetooth-serial-port#187]
Hello,

I am using NodeJS 10 and it seems that after all this time NAN finally seems to differ. I propose upgrading to N-API.

**Comment by eelcocramer** [comment]
I could add support for node v10 with minor changes. Please check if the code in the `next-release` branch works for you.

That said, I agree that the module needs to be updated and I would be happy to accept a PR that addresses this.

**Comment by eelcocramer** [comment]
@FrogTheFrog does the fix work for you?

**Comment by FrogTheFrog** [comment]
@eelcocramer Sorry for the delay, yes it does. Thanks.

**Comment by eelcocramer** [comment]
Thank you for getting back. I will add this to a release probably this week.

**Comment by eelcocramer** [comment]
Published as version 1.2.7 see #189
