### ISSUE TITLE
Is there SDP support?

### ISSUE THREAD

**Issue by xingrz** [eelcocramer/node-bluetooth-serial-port#19]
Hi all,

Sorry that I'm new to bluetooth.

Is node-blue-serial-port for RFCOMM?

Is there SDP support?

**Comment by mackwic** [comment]
Hi @eelcocramer ! Just a question by reading your comment here:
> The Bluetooth Special Interest Group (SIG) defined the UUID of the SPP Serial Port service to be 0x1101

So, why on osx it is redefined on `0x003`, which means RFCOMM ? ([ref](https://github.com/eelcocramer/node-bluetooth-serial-port/blob/master/src/osx/BluetoothWorker.mm#L29), I checked, I pass on the `#define` on my platform, osx 10.9).

I tried to recompile it with `0x1101` for science but no big changes...

**Comment by mackwic** [comment]
Ok, so [the linux source](https://github.com/eelcocramer/node-bluetooth-serial-port/blob/master/src/linux/BTSerialPortBinding.cc#L61) also use `0x003`, as `BTPROTO_RFCOMM` defined in `bluetooth.h` also resolve to `0x003` ([source](http://git.kernel.org/cgit/bluetooth/bluez.git/tree/lib/bluetooth.h#n48)).

How does this works ? I am confused...

**Comment by eelcocramer** [comment]
Hey @mackwic. I fucked up with that comment. The module tries to discover RFCOMM service with a base UUID of 0x0003 (per standard) and not the higher level SPP service UUID 0x1101. Service with that service UUID should have the RFCOMM base UUID and hence should be discovered by the module.

Does this help?

**Comment by mackwic** [comment]
Yes, it helps, thanks. It also means that I have to submit an issue. More details there.

**Comment by eelcocramer** [comment]
:-)
