### ISSUE TITLE
"symbol lookup error" when including inquire()

### ISSUE THREAD

**Issue by sundarSDI** [eelcocramer/node-bluetooth-serial-port#198]
Hi Team,

We are building an Electron app which connects to the Bluetooth to send and receive data, when we starting the app we are getting the bellow issue

symbol lookup error home/mark/Desktop/jan12_electronn/node_modules/bluetooth-serial-port/build/Release/BluetoothSerialPort.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE

when we remove the "btserial.inquire()", the app start normally, kindly provide any idea or suggestion to resolve the issue.

Thanks!!!
Sundar K.

**Comment by sundarSDI** [comment]
yes, I have that file in the location and my platform version is Ubuntu 18.0.4, please provide your suggestions. we really need to get this done by next week.

Thanks!!!
Sundar K.

**Comment by eelcocramer** [comment]
Honestly I don't have a clue what the problem may be. From the message it seems [event loop](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/) related. Maybe you should use `inquireSync` or run the `inquiry` in a separate thread?

I would appreciate if you could share your solution to this for future reference. Good luck in any case!
