### ISSUE TITLE
Can't connect to server with Android

### ISSUE THREAD

**Issue by yentheo** [eelcocramer/node-bluetooth-serial-port#202]
I'm trying to connect with the bluetooth server part of this library from an Android App. The node program is running on a Raspberry Pi (Raspian).

My code looks like this:
```TypeScript
this.bluetoothSerialPortServer
    .listen(
        client => this.connectedClient$.next(client),
        error => this.error$.next(error),
        {
            uuid: '94f39d29-7d6d-437d-973b-fba39e49d4ee',
            channel: 1
        }
    );
```
So I changed the UUID to a custom one and set the channel to default 1.
Now I have come to know there are some things wrong with the Bluetooth implementation of Android but when using this basic code:
```Java
try {
    BluetoothDevice device = bluetoothManager.getAdapter().getRemoteDevice("XX:XX:XX:XX:XX:XX");

    BluetoothSocket socket = device.createRfcommSocketToServiceRecord(UUID.fromString("94f39d29-7d6d-437d-973b-fba39e49d4ee"));

    if(!socket.isConnected()) {
        socket.connect();
    }
} catch (IOException e) {
    e.printStackTrace();
}
```
I alway get the IOException.
When I run this python bluetooth server on my Raspberry Pi, the Android code does work:
```python
import os
import glob
import time
from bluetooth import *

server_sock=BluetoothSocket(RFCOMM)
server_sock.bind(("",PORT_ANY))
server_sock.listen(1)

port = server_sock.getsockname()[1]

uuid = "94f39d29-7d6d-437d-973b-fba39e49d4ee"

advertise_service( server_sock, "TestServer",
                   service_id = uuid,
                   service_classes = [ uuid, SERIAL_PORT_CLASS ],
                   profiles = [ SERIAL_PORT_PROFILE ]
            )
while True:          
	print "Waiting for connection on RFCOMM channel %d" % port

	client_sock, client_info = server_sock.accept()
	print "Accepted connection from ", client_info
```
I can get the connection to work with this library, but only when hacking the Android code a bit like this:
```Java
try {
    BluetoothDevice device = bluetoothManager.getAdapter().getRemoteDevice("XX:XX:XX:XX:XX:XX");
    String name = device.getName();
    ParcelUuid[] uuids = device.getUuids();
    Method method;

    method = device.getClass().getMethod("createRfcommSocket", new Class[] { int.class } );
    BluetoothSocket socket = (BluetoothSocket) method.invoke(device, 1);

    if(!socket.isConnected()) {
        socket.connect();
    }
} catch (IOException e) {
    e.printStackTrace();
} catch (NoSuchMethodException e) {
    e.printStackTrace();
} catch (IllegalAccessException e) {
    e.printStackTrace();
} catch (InvocationTargetException e) {
    e.printStackTrace();
}
```
This way I can connect, but I'm not targeting any specific Port/Uuid/Service Descriptor... I don't know a lot about the bluetooth protocol and I find it very confusing.

I would like to be able to connect without having to use reflection and calling a hidden method in the Android app. I will use this hack for now, but maybe someone working with or on this library has any idea why this is the case.

Thanks in advance and thanks for the nice library!

**Comment by PsychoXIVI** [comment]
Are you sure you are running SDP service on server? Run the server and try
```
sudo sdptool browse local 
```
while it is running. Look for RFCOMM connection/channels.
