### ISSUE TITLE
question about process.stdin.on('data', function (data) {

### ISSUE THREAD

**Issue by PkNuAbrahim** [eelcocramer/node-bluetooth-serial-port#214]
i used your code and wanna connect 
app<->raspberry pi server <-> arduino bluetooth module

in this part

if(req.payload.toString() ==='0'){
           console.log('0');
            process.stdin.on('data', function (data) {
                var buf1 = Buffer.from(data);
                serial.write(buf1, function(err, bytesWritten){
                    if(err) console.log(err);
                });
            });

            serial.on('data', function(data) {
                console.log('Received: '+data );
            });
this code need console input but i want to send value without console input
how can i do?

**Comment by eelcocramer** [comment]
By putting a different value in the `buf1` variable. I would recommend you to start with a tutorial first to get familiar with the programming language. Here is a chapter on working with variables: https://javascript.info/variables

This issue tracker is used for issues related to the bluetooth module only. For more general questions about programming I would recommend you to search stackoverflow (https://stackoverflow.com/questions/tagged/javascript).
