### ISSUE TITLE
Question: Multiple invocations of same function in platform code?

### ISSUE THREAD

**Issue by PsychoXIVI** [eelcocramer/node-bluetooth-serial-port#220]
Why there are multiple invocations of the same function in platform code?

https://github.com/eelcocramer/node-bluetooth-serial-port/blob/1af7838e9c821cdee8a8e4bc6655cb9165b000be/src/linux/BTSerialPortBinding.cc#L236-L241

https://github.com/eelcocramer/node-bluetooth-serial-port/blob/1af7838e9c821cdee8a8e4bc6655cb9165b000be/src/linux/DeviceINQ.cc#L159-L166

https://github.com/eelcocramer/node-bluetooth-serial-port/blob/1af7838e9c821cdee8a8e4bc6655cb9165b000be/src/linux/BTSerialPortBindingServer.cc#L330-L336

I am new to this, and I was thinking for a while "maybe these must be called multiple times by number of fields, but there is only single call in `BTSerialPortBindingServer`... It makes no sense to me

**Comment by eelcocramer** [comment]
The lines seem to be redundant. I wrote this years ago so I’m not sure why I put these in anymore or if they can be left out.

**Comment by eelcocramer** [comment]
This was introduced back in the time NaN 2 and node v4 support was added by merging in changes from a forked repository that already added that support into this repository. A quick check makes me believe the lines are redundant and could be removed in a future version.

**Comment by eelcocramer** [comment]
These are now removed.
