### ISSUE TITLE
Segfault in `read` during GC

### ISSUE THREAD

**Issue by programmarchy** [eelcocramer/node-bluetooth-serial-port#28]
I think I've identified a segfault occurring in the `EIO_AfterRead` in BTSerialPortBinding.cc/.mm, during a garbage collection event. I was noticing crashes after reading data consistently from my Bluetooth device after about 30 minutes or so. After inspecting the crash log, I was able to narrow it down to the following lines:

```
void BTSerialPortBinding::EIO_AfterRead(uv_work_t *req) {
    read_baton_t *baton = static_cast<read_baton_t *>(req->data);

    TryCatch try_catch;

    Handle<Value> argv[2];

    if (baton->size < 0) {
        argv[0] = Exception::Error(String::New("Error reading from connection"));
        argv[1] = Undefined();
    } else {
        Buffer *buffer = Buffer::New(baton->size);
        memcpy_s(Buffer::Data(buffer), baton->size, baton->result, baton->size);
        Local<Object> globalObj = Context::GetCurrent()->Global();
        Local<Function> bufferConstructor = Local<Function>::Cast(globalObj->Get(String::New("Buffer")));
        Handle<Value> constructorArgs[3] = { buffer->handle_, Integer::New(baton->size), Integer::New(0) };
        Local<Object> resultBuffer = bufferConstructor->NewInstance(3, constructorArgs); // <---- Segfault occurring here: access violation (0xC0000005)

        argv[0] = Undefined();
        argv[1] = resultBuffer;
    }

    baton->cb->Call(Context::GetCurrent()->Global(), 2, argv);
    ...
```

What I believe is happening, is that the GC fires some time after `Buffer::New`, and before the line of the crash. Specifically, the `handle_` property in `buffer->handle_` is being invalidated by the GC, and then when trying to use that handle as the constructor argument, the segfault occurs.

I've been able to resolve this issue by following a workaround found online:

```
void BTSerialPortBinding::EIO_AfterRead(uv_work_t *req) {
    read_baton_t *baton = static_cast<read_baton_t *>(req->data);

    TryCatch try_catch;

    Handle<Value> argv[2];

    if (baton->size < 0) {
        argv[0] = Exception::Error(String::New("Error reading from connection"));
        argv[1] = Undefined();
    } else {
        Local<Object> globalObj = Context::GetCurrent()->Global();
        Local<Function> bufferConstructor = Local<Function>::Cast(globalObj->Get(String::New("Buffer")));
        Handle<Value> constructorArgs[1] = { Integer::New(baton->size) };
        Local<Object> resultBuffer = bufferConstructor->NewInstance(1, constructorArgs);
        memcpy(node::Buffer::Data(resultBuffer), baton->result, baton->size);
        argv[0] = Undefined();
        argv[1] = resultBuffer;
    }

    baton->cb->Call(Context::GetCurrent()->Global(), 2, argv);
    ...
```

Based on my preliminary testing, this seems to work. However, a tradeoff is being made here, I believe: which is the patched version is using a "slow buffer" where the previous version was using a "fast buffer".

A related issue has been posted on node core repo here: https://github.com/joyent/node/issues/5864

The workaround posted by Jonathan Wiepert here: http://www.samcday.com.au/blog/2011/03/03/creating-a-proper-buffer-in-a-node-c-addon/

Pull request forthcoming, but curious to hear any thoughts or better solutions to this problem.

**Comment by eelcocramer** [comment]
The fix for this issue was [incorrect](https://github.com/nodejs/nan/issues/440). I've updated the code in the `next-release` branch and will push this branch into master (and npm) after the weekend.

@programmarchy: If you have time (and interest) to test if this branch does not re-introduce this issue for you I would appreciate it!
