### ISSUE TITLE
Failed Install (Windows)

### ISSUE THREAD

**Issue by VVScott** [eelcocramer/node-bluetooth-serial-port#32]
Hey there, I am getting errors when I try and run npm install bluetooth-serial-port.

I have Python 2.7 and I installed Visual Studio 2013 but I wasn't sure exactly how the prerequisite works for that.

The cmd line error report says a lot of stuff, including this.

Failed at the bluetooth-serial-port@1.1.3 install script.
Tell the author that this fails on your system:
node-gyp configure build

This is the start of the npm debug log.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files (x86)\nodejs\\node.exe',
1 verbose cli   'C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bluetooth-serial-port' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink C:\Program Files (x86)\nodejs\node.exe
5 verbose cache add [ 'bluetooth-serial-port', null ]
6 verbose cache add name=undefined spec="bluetooth-serial-port" args=["bluetooth-serial-port",null]

etc...

**Comment by zavitax** [comment]
Install fails for me with:
> npm install bluetooth-serial-port

- Running from Developer Command Prompt for VS 2017
- Python accessible from command line:
> Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win32

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bluetooth-serial-port' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose npm-session 61f152799112b18e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/bluetooth-serial-port 421ms (from cache)
8 silly pacote tag manifest for bluetooth-serial-port@latest fetched in 489ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule bluetooth-serial-port@2.1.5 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/bindings 84ms (from cache)
15 silly pacote range manifest for bindings@1.2.x fetched in 88ms
16 silly resolveWithNewModule bindings@1.2.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/nan 235ms (from cache)
18 silly pacote tag manifest for nan@latest fetched in 239ms
19 silly resolveWithNewModule nan@2.8.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 1007ms (from cache)
21 silly pacote range manifest for @types/node@^7.0.10 fetched in 1012ms
22 silly resolveWithNewModule @types/node@7.0.52 checking installable status
23 silly currentTree base64gen@1.0.0
23 silly currentTree `-- pngjs2@2.0.0
24 silly idealTree base64gen@1.0.0
24 silly idealTree +-- @types/node@7.0.52
24 silly idealTree +-- bindings@1.2.1
24 silly idealTree +-- bluetooth-serial-port@2.1.5
24 silly idealTree +-- nan@2.8.0
24 silly idealTree `-- pngjs2@2.0.0
25 silly install generateActionsToTake
26 silly diffTrees action count 4
27 silly diffTrees add @types/node@7.0.52
28 silly diffTrees add bindings@1.2.1
29 silly diffTrees add nan@2.8.0
30 silly diffTrees add bluetooth-serial-port@2.1.5
31 silly decomposeActions action count 32
32 silly decomposeActions fetch @types/node@7.0.52
33 silly decomposeActions extract @types/node@7.0.52
34 silly decomposeActions preinstall @types/node@7.0.52
35 silly decomposeActions build @types/node@7.0.52
36 silly decomposeActions install @types/node@7.0.52
37 silly decomposeActions postinstall @types/node@7.0.52
38 silly decomposeActions finalize @types/node@7.0.52
39 silly decomposeActions refresh-package-json @types/node@7.0.52
40 silly decomposeActions fetch bindings@1.2.1
41 silly decomposeActions extract bindings@1.2.1
42 silly decomposeActions preinstall bindings@1.2.1
43 silly decomposeActions build bindings@1.2.1
44 silly decomposeActions install bindings@1.2.1
45 silly decomposeActions postinstall bindings@1.2.1
46 silly decomposeActions finalize bindings@1.2.1
47 silly decomposeActions refresh-package-json bindings@1.2.1
48 silly decomposeActions fetch nan@2.8.0
49 silly decomposeActions extract nan@2.8.0
50 silly decomposeActions preinstall nan@2.8.0
51 silly decomposeActions build nan@2.8.0
52 silly decomposeActions install nan@2.8.0
53 silly decomposeActions postinstall nan@2.8.0
54 silly decomposeActions finalize nan@2.8.0
55 silly decomposeActions refresh-package-json nan@2.8.0
56 silly decomposeActions fetch bluetooth-serial-port@2.1.5
57 silly decomposeActions extract bluetooth-serial-port@2.1.5
58 silly decomposeActions preinstall bluetooth-serial-port@2.1.5
59 silly decomposeActions build bluetooth-serial-port@2.1.5
60 silly decomposeActions install bluetooth-serial-port@2.1.5
61 silly decomposeActions postinstall bluetooth-serial-port@2.1.5
62 silly decomposeActions finalize bluetooth-serial-port@2.1.5
63 silly decomposeActions refresh-package-json bluetooth-serial-port@2.1.5
64 silly install executeActions
65 silly doSerial global-install 32
66 verbose correctMkdir C:\Users\ilya7\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
67 verbose lock using C:\Users\ilya7\AppData\Roaming\npm-cache\_locks\staging-e092d313b88618f9.lock for C:\Shared\TalkBack\Dev\Bluetooth\node_modules\.staging
68 silly doParallel extract 32
69 silly extract @types/node@7.0.52
70 silly pacote trying @types/node@https://registry.npmjs.org/@types/node/-/node-7.0.52.tgz by hash: sha512-jjpyQsKGsOF/wUElNjfPULk+d8PKvJOIXk3IUeBYYmNCy5dMWfrI+JiixYNw8ppKOlcRwWTXFl0B+i5oGrf95Q==
71 silly extract bindings@1.2.1
72 silly pacote trying bindings@https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz by hash: sha1-FK1hE4EtLTfXLme0ystLtyZQXxE=
73 silly extract nan@2.8.0
74 silly pacote trying nan@https://registry.npmjs.org/nan/-/nan-2.8.0.tgz by hash: sha1-7XFfP+neArV6XmJS2QqWZ14fCFo=
75 silly extract bluetooth-serial-port@2.1.5
76 silly pacote trying bluetooth-serial-port@https://registry.npmjs.org/bluetooth-serial-port/-/bluetooth-serial-port-2.1.5.tgz by hash: sha1-BX3dkMSYzfjRHjqOkADDmLH45XQ=
77 silly pacote bindings@https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz extracted to C:\Shared\TalkBack\Dev\Bluetooth\node_modules\.staging\bindings-4ec019bc by content address 84ms
78 silly pacote @types/node@https://registry.npmjs.org/@types/node/-/node-7.0.52.tgz extracted to C:\Shared\TalkBack\Dev\Bluetooth\node_modules\.staging\@types\node-cc34445d by content address 102ms
79 silly pacote nan@https://registry.npmjs.org/nan/-/nan-2.8.0.tgz extracted to C:\Shared\TalkBack\Dev\Bluetooth\node_modules\.staging\nan-7b06c1c8 by content address 160ms
80 silly pacote bluetooth-serial-port@https://registry.npmjs.org/bluetooth-serial-port/-/bluetooth-serial-port-2.1.5.tgz extracted to C:\Shared\TalkBack\Dev\Bluetooth\node_modules\.staging\bluetooth-serial-port-6438b315 by content address 160ms
81 silly doReverseSerial unbuild 32
82 silly doSerial remove 32
83 silly doSerial move 32
84 silly doSerial finalize 32
85 silly finalize C:\Shared\TalkBack\Dev\Bluetooth\node_modules\@types\node
86 silly finalize C:\Shared\TalkBack\Dev\Bluetooth\node_modules\bindings
87 silly finalize C:\Shared\TalkBack\Dev\Bluetooth\node_modules\nan
88 silly finalize C:\Shared\TalkBack\Dev\Bluetooth\node_modules\bluetooth-serial-port
89 silly doParallel refresh-package-json 32
90 silly refresh-package-json C:\Shared\TalkBack\Dev\Bluetooth\node_modules\@types\node
91 silly refresh-package-json C:\Shared\TalkBack\Dev\Bluetooth\node_modules\bindings
92 silly refresh-package-json C:\Shared\TalkBack\Dev\Bluetooth\node_modules\nan
93 silly refresh-package-json C:\Shared\TalkBack\Dev\Bluetooth\node_modules\bluetooth-serial-port
94 silly doParallel preinstall 32
95 silly preinstall @types/node@7.0.52
96 info lifecycle @types/node@7.0.52~preinstall: @types/node@7.0.52
97 silly preinstall bindings@1.2.1
98 info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
99 silly preinstall nan@2.8.0
100 info lifecycle nan@2.8.0~preinstall: nan@2.8.0
101 silly preinstall bluetooth-serial-port@2.1.5
102 info lifecycle bluetooth-serial-port@2.1.5~preinstall: bluetooth-serial-port@2.1.5
103 silly doSerial build 32
104 silly build @types/node@7.0.52
105 info linkStuff @types/node@7.0.52
106 silly linkStuff @types/node@7.0.52 has C:\Shared\TalkBack\Dev\Bluetooth\node_modules as its parent node_modules
107 verbose linkBins @types/node@7.0.52
108 verbose linkMans @types/node@7.0.52
109 silly build bindings@1.2.1
110 info linkStuff bindings@1.2.1
111 silly linkStuff bindings@1.2.1 has C:\Shared\TalkBack\Dev\Bluetooth\node_modules as its parent node_modules
112 verbose linkBins bindings@1.2.1
113 verbose linkMans bindings@1.2.1
114 silly build nan@2.8.0
115 info linkStuff nan@2.8.0
116 silly linkStuff nan@2.8.0 has C:\Shared\TalkBack\Dev\Bluetooth\node_modules as its parent node_modules
117 verbose linkBins nan@2.8.0
118 verbose linkMans nan@2.8.0
119 silly build bluetooth-serial-port@2.1.5
120 info linkStuff bluetooth-serial-port@2.1.5
121 silly linkStuff bluetooth-serial-port@2.1.5 has C:\Shared\TalkBack\Dev\Bluetooth\node_modules as its parent node_modules
122 verbose linkBins bluetooth-serial-port@2.1.5
123 verbose linkMans bluetooth-serial-port@2.1.5
124 silly doSerial global-link 32
125 silly doParallel update-linked 32
126 silly doSerial install 32
127 silly install @types/node@7.0.52
128 info lifecycle @types/node@7.0.52~install: @types/node@7.0.52
129 silly install bindings@1.2.1
130 info lifecycle bindings@1.2.1~install: bindings@1.2.1
131 silly install nan@2.8.0
132 info lifecycle nan@2.8.0~install: nan@2.8.0
133 silly install bluetooth-serial-port@2.1.5
134 info lifecycle bluetooth-serial-port@2.1.5~install: bluetooth-serial-port@2.1.5
135 verbose lifecycle bluetooth-serial-port@2.1.5~install: unsafe-perm in lifecycle true
136 verbose lifecycle bluetooth-serial-port@2.1.5~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Shared\TalkBack\Dev\Bluetooth\node_modules\bluetooth-serial-port\node_modules\.bin;C:\Shared\TalkBack\Dev\Bluetooth\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.5;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;C:\code\depot_tools;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;c:\Windows\System32\wbem;C:\Local\Programs\Python\Python35\Scripts\;C:\Local\Programs\Python\Python35\;C:\Program Files (x86)\WinSCP\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Skype\Phone\;C:\Local\Programs\Perl\c\bin;C:\Local\Programs\Perl\perl\site\bin;C:\Local\Programs\Perl\perl\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\tools\go\bin;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files\CMake\bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\Library\bin;C:\Program Files\Git\cmd;C:\Chromium\src\depot_tools;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Xoreax\IncrediBuild;C:\Program Files\nodejs\;C:\Code\depot_tools;C:\Ruby23-x64\bin;C:\Users\ilya7\.dnx\bin;C:\Users\ilya7\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ilya7\AppData\Roaming\Composer\vendor\bin;c:\Program Files\git\bin;C:\local\programs\cmdline;C:\Program Files (x86)\PostgreSQL Frontend\bin;c:\local\Programs\CmdLine;c:\windows\system32;c:\Program Files (x86)\PHP\v5.6;C:\Users\ilya7\AppData\Local\Programs\Fiddler;C:\Users\ilya7\AppData\Local\Microsoft\WindowsApps;C:\tools\mingw64\bin;C:\Chromium\src\depot_tools;C:\Users\ilya7\AppData\Roaming\npm
137 verbose lifecycle bluetooth-serial-port@2.1.5~install: CWD: C:\Shared\TalkBack\Dev\Bluetooth\node_modules\bluetooth-serial-port
138 silly lifecycle bluetooth-serial-port@2.1.5~install: Args: [ '/d /s /c', 'node-gyp configure build' ]
139 silly lifecycle bluetooth-serial-port@2.1.5~install: Returned: code: 1  signal: null
140 info lifecycle bluetooth-serial-port@2.1.5~install: Failed to exec install script
141 verbose unlock done using C:\Users\ilya7\AppData\Roaming\npm-cache\_locks\staging-e092d313b88618f9.lock for C:\Shared\TalkBack\Dev\Bluetooth\node_modules\.staging
142 silly saveTree base64gen@1.0.0
142 silly saveTree +-- bluetooth-serial-port@2.1.5
142 silly saveTree | +-- @types/node@7.0.52
142 silly saveTree | +-- bindings@1.2.1
142 silly saveTree | `-- nan@2.8.0
142 silly saveTree `-- pngjs2@2.0.0
143 warn base64gen@1.0.0 No description
144 warn base64gen@1.0.0 No repository field.
145 verbose stack Error: bluetooth-serial-port@2.1.5 install: `node-gyp configure build`
145 verbose stack Exit status 1
145 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
145 verbose stack     at EventEmitter.emit (events.js:160:13)
145 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
145 verbose stack     at ChildProcess.emit (events.js:160:13)
145 verbose stack     at maybeClose (internal/child_process.js:943:16)
145 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
146 verbose pkgid bluetooth-serial-port@2.1.5
147 verbose cwd C:\Shared\TalkBack\Dev\Bluetooth
148 verbose Windows_NT 10.0.16299
149 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bluetooth-serial-port"
150 verbose node v9.4.0
151 verbose npm  v5.6.0
152 error code ELIFECYCLE
153 error errno 1
154 error bluetooth-serial-port@2.1.5 install: `node-gyp configure build`
154 error Exit status 1
155 error Failed at the bluetooth-serial-port@2.1.5 install script.
155 error This is probably not a problem with npm. There is likely additional logging output above.
156 verbose exit [ 1, true ]
