### ISSUE TITLE
I encountered a fatal error using node-bluetooth-serial-port

### ISSUE THREAD

**Issue by Liting1** [eelcocramer/node-bluetooth-serial-port#344]
windows10
node: 12.20.2
node-gyp: 8.2.0
vs 2019
python 3.9

I encountered an error while running the following code

```
var btSerial = new (require("node-bluetooth-serial-port").BluetoothSerialPort)();
btSerial.on("found", function (address, name) {
  btSerial.findSerialPortChannel(
    address,
    function (channel) {
      btSerial.connect(
        address,
        channel,
        function () {
          console.log("connected");
          btSerial.write(Buffer.from("my data", "utf-8"), function (
            err,
            bytesWritten
          ) {
            if (err) console.log(err);
          });
          btSerial.on("data", function (buffer) {
            console.log(buffer.toString("utf-8"));
          });
        },
        function () {
          console.log("cannot connect");
        }
      );
      // close the connection when you're ready
      btSerial.close();
    },
    function () {
      console.log("found nothing");
    }
  );
});
btSerial.inquire();
```

ERROE

for (const device of devices) {
                           ^

TypeError: devices is not iterable
    at BluetoothSerialPort.finish (E:\zkt\doc\test\cmd\node_modules\node-bluetooth-serial-port\lib\bluetooth-serial-port.js:36:28)
[Finished in 6.8s with exit code 1]

**Comment by Liting1** [comment]
I took care of it myself

Here's the problem，The correct answer would be the following

![image](https://user-images.githubusercontent.com/33544236/132131259-cd7d5c3f-7ca3-485a-8788-e3f2f72fa624.png)

Too bad you wrote it like this

![image](https://user-images.githubusercontent.com/33544236/132131335-61b2a632-ee6d-427e-8b5e-25eba5ee5c21.png)

**Comment by Liting1** [comment]
@eelcocramer

**Comment by eelcocramer** [comment]
I cannot find the code you quoting in the repo. Can you link to the line?

**Comment by Liting1** [comment]
@eelcocramer  This is line 35

https://github.com/tinyprinter/node-bluetooth-serial-port/blob/master/lib/bluetooth-serial-port.js

**Comment by Liting1** [comment]
I am looking at the wrong place

**Comment by Liting1** [comment]
@Tinyprinter
