### ISSUE TITLE
Windows 8.1 Pro with Visual Studio Express 2013

### ISSUE THREAD

**Issue by TrevorMurphy** [eelcocramer/node-bluetooth-serial-port#38]
Problem installing on a windows8 machine, python and VS installed.

npm install fails during node-gyp build phase when linking. 
LINK: fatal error LNK1104 cannot open file 'LIBCMT.lib'

Using VS Express 2013, on a brand new Windows 8.1 pro machine with windows SDK installed ( to resolve earlier issue with missing headers )

Also, once this is resolved, any help on which binaries need to be included into a distribution package would be appreciated also.

Help appreciated :)

**Comment by andyhu** [comment]
By the way, it might be not needed to install VS 2013 Enterprise. You can install VS 2013 Express for Desktop instead.

**Comment by dfogas** [comment]
Thumbs up for this post, installing MS VS for desktop 2013 fixed this problem for me(I had only VS for Windows 2013), though it was on different project. thanks @andyhu and others as well!
