### ISSUE TITLE
npm install gyp build error

### ISSUE THREAD

**Issue by TylerYang** [eelcocramer/node-bluetooth-serial-port#44]
Hey guys, I try to run <code>npm install bluetooth-serial-port</code> in windows 7(64bit) command line.
Then throw this error message:

<code>
PS E:\study\ble-light> npm install bluetooth-serial-port
npm WARN package.json your-app@0.1.0 No description
npm WARN package.json your-app@0.1.0 No repository field.
npm WARN package.json your-app@0.1.0 No README data

> bluetooth-serial-port@1.1.4 install E:\study\ble-light\node_modules\bluetooth-serial-port
> node-gyp configure build
> E:\study\ble-light\node_modules\bluetooth-serial-port>node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure build
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   BluetoothSerialPort.cc
>   DeviceINQ.cc
>   BTSerialPortBinding.cc
>   BluetoothHelpers.cc
> C:\Users\win7.node-gyp\0.10.32\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [E:\study\ble-light\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
>           with
>           [
>               T=v8::Object
>           ]
> C:\Users\win7.node-gyp\0.10.32\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [E:\study\ble-light\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
>           with
>           [
>               T=v8::Object
>           ]
> C:\Users\win7.node-gyp\0.10.32\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [E:\study\ble-light\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
>           with
>           [
>               T=v8::Object
>           ]
> LINK : fatal error LNK1181: cannot open input file 'gdi32.lib' [E:\study\ble-light\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "node" "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "build"
> gyp ERR! cwd E:\study\ble-light\node_modules\bluetooth-serial-port
> gyp ERR! node -v v0.10.32
> gyp ERR! node-gyp -v v1.0.1
> gyp ERR! not ok
> </code>
> <code>
> npm ERR! bluetooth-serial-port@1.1.4 install: `node-gyp configure build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bluetooth-serial-port@1.1.4 install script.
> npm ERR! This is most likely a problem with the bluetooth-serial-port package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp configure build
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls bluetooth-serial-port
> npm ERR! There is likely additional logging output above.
> npm ERR! System Windows_NT 6.1.7601
> npm ERR! command "D:\Program Files\nodejs\\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "bluetooth-seri  
> npm ERR! cwd E:\study\ble-light  
> npm ERR! node -v v0.10.32  
> npm ERR! npm -v 1.4.28  
> npm ERR! code ELIFECYCLE  
> npm ERR! not ok code 0  
> </code>

Can somebody give me a hand?

**Comment by trvajjala** [comment]
sudp npm install bluetooth-serial-port --msvs_version=2012 not workingon mac

**Comment by eelcocramer** [comment]
This issue is about building on Windows (msvs stands for microsoft visual studio). For mac you should use npm install bluetooth-serial-port. If this does not work please open up a new issue and post the log of your build. 

Thanks.

**Comment by czepluch** [comment]
What about linux? ´npm install bluetooth-serial-port´ doesn't seem to work.

**Comment by eelcocramer** [comment]
node v4.0 is not supported yet. A pr is pending. Expect a fix somewhere next week

**Comment by czepluch** [comment]
Yeah, I just found the PR. Got it working. Thanks.
