### ISSUE TITLE
Check if version 1.2 compiles on windows

### ISSUE THREAD

**Issue by eelcocramer** [eelcocramer/node-bluetooth-serial-port#53]
... and fix compilation errors if needed.

**Comment by RIAEvangelist** [comment]
Any news on this? If not, do you need it tested on any particular windows platforms?

**Comment by eelcocramer** [comment]
Not yet. It would be great if you can try compiling the module on windows (8 preferably)  with both node v0.10 and v0.11 (and maybe v0.8).

**Comment by Globegitter** [comment]
I just tried to compile this (well, run `node-gyp configure`) and with the full Ultimate Version of VS 2015 I am getting:
![screen shot 2015-01-30 at 12 14 15](https://cloud.githubusercontent.com/assets/2580254/5975509/88c586d2-a879-11e4-9f5a-0175695b2db5.png)

Trying to install now what it says in the message.

**Comment by eelcocramer** [comment]
Thanks for the update. With the correct setup the `configure` should work fine. I've only made changes to the sources to make it the module compatible with both node 0.10.x and 0.11.x.

**Comment by Globegitter** [comment]
Yep, I think the issue is that things are not compatible yet with VS 2015. Will see if I can fix that relatively painfree.

**Comment by Globegitter** [comment]
Did install VS2010 and now getting the following issue:
![screen shot 2015-01-30 at 13 30 37](https://cloud.githubusercontent.com/assets/2580254/5976318/474c7ca0-a884-11e4-87d8-219c33073b4f.png)

**Comment by eelcocramer** [comment]
Thank you. I will look into it later today and push a fix. You help is greatly apreciated!

**Comment by eelcocramer** [comment]
Can you `git pull` and try again? I've pushed new code that hopefully fixes this compile issue.

**Comment by Globegitter** [comment]
Yep, I think we are down to the next error now. Thanks for taking quite a bit of time to get back:
![screen shot 2015-01-30 at 18 40 08](https://cloud.githubusercontent.com/assets/2580254/5981136/7e774e3c-a8af-11e4-8b4b-2e9bdc4b8d44.png)

**Comment by Globegitter** [comment]
I just changed the line 112 to `argv[1] = NanNew(static_cast<int32_t>(data->result));` and it actually compiled. Just trying out if it works.

**Comment by eelcocramer** [comment]
I think node 0.11 needs the other cast. I've pushed another commit that hopefully fixes this as well.

**Comment by Globegitter** [comment]
Compiled and working now! Thanks :)

**Comment by eelcocramer** [comment]
Care to try and compile it with node v0.11.x? If it compiles and runs there as well I will release an new version that adds windows support again.

**Comment by eelcocramer** [comment]
Confirmed thanks to #58 will be part of upcoming 1.2.2 release.
