### ISSUE TITLE
What is the behavior on power loss ?

### ISSUE THREAD

**Issue by gautaz** [eelcocramer/node-bluetooth-serial-port#66]
Hello,

I am wondering what should be the behavior of the bluetooth-serial-port library when a device it is already paired with suffers a power loss.
From my experiments, the library returns an error on writing ("Write was unsuccessful") but is there a way to be more proactive, i.e. listening on a particular event emitted by the library ?
It seems that neither "closed" nor "failure" are emitted in this particular case...

**Comment by eelcocramer** [comment]
Unfortunately, as far as I know, there is no way to do that. What the library does is sending the event as soon as the OS signals the library. If there is no event from the OS there is nothing to send upwards.

You could implement your own `keep-alive` messages if you want...

**Comment by gautaz** [comment]
Thanks @eelcocramer for the `keep-alive` idea, I'll try this for now.

**Comment by eelcocramer** [comment]
Adding this to the FAQ for future reference.
