### ISSUE TITLE
Can I build a server side app using this library?

### ISSUE THREAD

**Issue by onecue** [eelcocramer/node-bluetooth-serial-port#78]
Hi developers.

I want to build a simple server side app which communicate with smart phones.

My device open a bluetooth server app, then my smart phone search devices and connect to the device.

Is it possible?

**Comment by eelcocramer** [comment]
This is not possible using this library as it is client side only. Please check issue #69.

**Comment by onecue** [comment]
Thanks, we decide to change a dev. language from the node.js to the python.

**Comment by eelcocramer** [comment]
As from v1.3.1 this module has (experimental) server support available for Linux.
