### ISSUE TITLE
Question about the time it takes to detect disconnection

### ISSUE THREAD

**Issue by reyiyo** [eelcocramer/node-bluetooth-serial-port#80]
Hi! I'm writing some code to detect when the connection with the BT device is lost and try to recconnect. I use the 'failure' or 'closed' events, but the problem is:

While I'm reading data from the device (with ~300 pkg/sec), I power it off and it takes at least 17 seconds to emit the closed event.

The question is if do you know why may this happen and if is there any setting I can change so I can receive the 'closed' event earlier.

I'm on linux (debian) with the latest version of node-bluetooth-serial-port. I don't know if I'm the only one with this problem.

Thanks a lot!

**Comment by Nullpo** [comment]
+1

**Comment by eelcocramer** [comment]
Bluetooth is a protocol that is designed to work over an unreliable medium (i.e. radio connection), and as such has to tolerate errors in (or loss of) packets. For this reason it will take a significant time before the Bluetooth stack declares it has given up and disconnected the device, as you have found.

Please see #66 for a possible strategy that your program can follow to get around this issue.
