### ISSUE TITLE
Signal Strength

### ISSUE THREAD

**Issue by tomdanvers** [eelcocramer/node-bluetooth-serial-port#84]
Hello,
Thanks for this great node module its excellent!
Is there any way of determining the signal strength of the devices that .inquire() finds?
Thanks,
Tom

**Comment by eelcocramer** [comment]
Hi Tom,

Thanks!

Currently this module does not support RSSI and I've currently no plans to implement this. However I'm happy to merge a PR for this function :+1: :-)
